### ISSUE TITLE
搬运工

### ISSUE THREAD

**Issue by butlanys** [HWR20080716/UnhideXueHai#1]
搬运的还是我发给你的资源，还不标明出处……

**Comment by Hwenray** [comment]
> 搬运的还是我发给你的资源，还不标明出处……

az什么意思啊，我自己上传设备导出的apk包的，twrp你也只是分享了xda论坛的链接吧。。。（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）
nnd还要我去Google drive去下载
不过确实是我疏忽了，有空去改
（恼~本来就只是分享下资源而已）

**Comment by butlanys** [comment]
> > 搬运的还是我发给你的资源，还不标明出处……
> 
> az什么意思啊，我自己上传设备导出的apk包的，twrp你也只是分享了xda论坛的链接吧。。。（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）
> nnd还要我去Google drive去下载
> 不过确实是我疏忽了，有空去改
> （恼~本来就只是分享下资源而已）

那下次你自己找吧😅

**Comment by Hwenray** [comment]
> > > 搬运的还是我发给你的资源，还不标明出处……
> > 
> > 
> > az什么意思啊，我自己上传设备导出的apk包的，twrp你也只是分享了xda论坛的链接吧。。。（[https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）](https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/%EF%BC%89%EF%BC%88https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/%EF%BC%89)
> > nnd还要我去Google drive去下载
> > 不过确实是我疏忽了，有空去改
> > （恼~本来就只是分享下资源而已）
> 
> 那下次你自己找吧😅

还有三十天，再也不™的搞xh了（emoji识别成功-windows）

**Comment by butlanys** [comment]
> > > > 搬运的还是我发给你的资源，还不标明出处……
> > > 
> > > 
> > > az什么意思啊，我自己上传设备导出的apk包的，twrp你也只是分享了xda论坛的链接吧。。。（[https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）（https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/）](https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/%EF%BC%89%EF%BC%88https://forum.xda-developers.com/t/pledge-for-twrp-for-tab-a-with-s-pen-sm-p205.4175655/%EF%BC%89)
> > > nnd还要我去Google drive去下载
> > > 不过确实是我疏忽了，有空去改
> > > （恼~本来就只是分享下资源而已）
> > 
> > 那下次你自己找吧😅
> 
> 还有三十天，再也不™的搞xh了（emoji识别成功-windows）

那我帮你上报xh老师，帮你刷回去😂

**Comment by Hwenray** [comment]
> 

这机锋论坛真是逊啦，很多都是搬运XDA论坛的
